# Generated by Django 5.2.12 on 2026-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("portfolio_url", models.URLField(blank=True)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AlterField(
            model_name="artwork",
            name="medium",
            field=models.CharField(
                choices=[
                    ("painting", "Painting"),
                    ("drawing", "Drawing"),
                    ("printmaking", "Printmaking"),
                    ("ceramics", "Ceramics"),
                    ("sculpture", "Sculpture"),
                    ("photography", "Photography"),
                    ("mixed_media", "Mixed Media"),
                    ("glass", "Glass"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
