# Generated by Django 5.2.12 on 2026-03-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_sellerapplication_alter_artwork_medium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_email", models.EmailField(max_length=254)),
                ("stripe_session_id", models.CharField(max_length=200, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="marketplace.artwork",
                    ),
                ),
            ],
        ),
    ]
