# Generated by Django 5.2.12 on 2026-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
